
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PX.Models
{

using System;
    using System.Collections.Generic;
    
public partial class parqueo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public parqueo()
    {

        this.Ticket = new HashSet<Ticket>();

    }


    public int Id { get; set; }

    public string Nombre { get; set; }

    public int Ubicacion { get; set; }

    public int Precio { get; set; }

    public int Capacidad { get; set; }

    public string Estado { get; set; }

    public int Parqueo_Vehiculo { get; set; }



    public virtual Vehiculo_parqueo Vehiculo_parqueo { get; set; }

    public virtual Ubicacion Ubicacion1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Ticket> Ticket { get; set; }

}

}
