
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PX.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Ticket
{

    public int Id { get; set; }

    public int Parqueo { get; set; }

    public System.DateTime Fecha { get; set; }

    public int Total { get; set; }



    public virtual parqueo parqueo1 { get; set; }

}

}
